### ISSUE TITLE
eChartType.ColumnStacked

### ISSUE THREAD

**Issue by ShiYuHe** [EPPlusSoftware/EPPlus.Sample.NetCore#1]
no this sample

**Comment by JanKallman** [comment]
It's pretty much the same as this sample...
https://github.com/EPPlusSoftware/EPPlus.Sample.NetCore/blob/master/15-ChartsAndThemes/ThreeDimensionalCharts.cs

**Comment by ShiYuHe** [comment]
> It's pretty much the same as this sample...
> https://github.com/EPPlusSoftware/EPPlus.Sample.NetCore/blob/master/15-ChartsAndThemes/ThreeDimensionalCharts.cs

ok,let me try
