### ISSUE TITLE
Can't run the project in Visual Studio

### ISSUE THREAD

**Issue by Dark-Yox** [EPPlusSoftware/EPPlus.Sample.NetCore#6]
IDE : Visual Studio 2019
EPPlus : 5.7.5

|Severity|Code|Description|File|Line|
|--------|----|-----------|----|----|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\08-SalesReport\SalesReport.cs|115|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\08-SalesReport\SalesReport.cs|116|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\08-SalesReport\SalesReport.cs|117|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\08-SalesReport\SalesReport.cs|118|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\09-PerformanceAndProtection\PerformanceAndProtectionSample.cs|97|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Rows' and no accessible extension method 'Rows' accepting a first argument of type 'ExcelWorksheet' could be found|\16-Sparklines\SparklinesSample.cs|75|
|Error|CS1061|'ExcelChartLegend' does not contain a definition for 'Entries' and no accessible extension method 'Entries' accepting a first argument of type 'ExcelChartLegend' could be found|\17-FXReportFromDatabase\FXReportFromDatabase.cs|136|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\18-PivotTables\PivotTablesSample.cs|324|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\19-EncryptionAndProtection\EncryptionAndProtectionSample.cs|69|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\19-EncryptionAndProtection\EncryptionAndProtectionSample.cs|70|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\19-EncryptionAndProtection\EncryptionAndProtectionSample.cs|71|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|76|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|77|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|78|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|79|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|82|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|83|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Rows' and no accessible extension method 'Rows' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|405|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Rows' and no accessible extension method 'Rows' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|419|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Rows' and no accessible extension method 'Rows' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|439|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Rows' and no accessible extension method 'Rows' accepting a first argument of type 'ExcelWorksheet' could be found|\20-CreateFileSystemReport\CreateAFileSystemReport.cs|452|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Rows' and no accessible extension method 'Rows' accepting a first argument of type 'ExcelWorksheet' could be found|\21-VBA\WorkingWithVbaSample.cs|173|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\26-FormControls\FormControlsSample.cs|131|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\26-FormControls\FormControlsSample.cs|132|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Rows' and no accessible extension method 'Rows' accepting a first argument of type 'ExcelWorksheet' could be found|\26-FormControls\FormControlsSample.cs|135|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillNumber' and no accessible extension method 'FillNumber' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|52|
|Error|CS0117|'ExcelRangeCopyOptionFlags' does not contain a definition for 'ExcludeHyperLinks'|\30-WorkingWithRanges\CopyRangeSample.cs|80|
|Error|CS0117|'ExcelRangeCopyOptionFlags' does not contain a definition for 'ExcludeMergedCells'|\30-WorkingWithRanges\CopyRangeSample.cs|84|
|Error|CS0117|'ExcelRangeCopyOptionFlags' does not contain a definition for 'ExcludeStyles'|\30-WorkingWithRanges\CopyRangeSample.cs|84|
|Error|CS0117|'ExcelRangeCopyOptionFlags' does not contain a definition for 'ExcludeHyperLinks'|\30-WorkingWithRanges\CopyRangeSample.cs|84|
|Error|CS0117|'ExcelRangeCopyOptionFlags' does not contain a definition for 'ExcludeValues'|\30-WorkingWithRanges\CopyRangeSample.cs|87|
|Error|CS0117|'ExcelRangeCopyOptionFlags' does not contain a definition for 'ExcludeHyperLinks'|\30-WorkingWithRanges\CopyRangeSample.cs|87|
|Error|CS1061|'ExcelRange' does not contain a definition for 'CopyStyles' and no accessible extension method 'CopyStyles' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|100|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|117|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|118|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|119|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillNumber' and no accessible extension method 'FillNumber' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|121|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillDateTime' and no accessible extension method 'FillDateTime' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|122|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillNumber' and no accessible extension method 'FillNumber' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|123|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\CopyRangeSample.cs|124|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillNumber' and no accessible extension method 'FillNumber' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|43|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillNumber' and no accessible extension method 'FillNumber' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|47|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillNumber' and no accessible extension method 'FillNumber' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|51|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillDateTime' and no accessible extension method 'FillDateTime' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|73|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillDateTime' and no accessible extension method 'FillDateTime' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|78|
|Error|CS0103|The name 'eDateTimeUnit' does not exist in the current context|\30-WorkingWithRanges\FillRangeSample.cs|78|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillDateTime' and no accessible extension method 'FillDateTime' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|88|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillDateTime' and no accessible extension method 'FillDateTime' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|120|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\30-WorkingWithRanges\FillRangeSample.cs|128|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|142|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|146|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|150|
|Error|CS1061|'ExcelRange' does not contain a definition for 'FillList' and no accessible extension method 'FillList' accepting a first argument of type 'ExcelRange' could be found|\30-WorkingWithRanges\FillRangeSample.cs|159|
|Error|CS1061|'ExcelWorksheet' does not contain a definition for 'Columns' and no accessible extension method 'Columns' accepting a first argument of type 'ExcelWorksheet' could be found|\30-WorkingWithRanges\FillRangeSample.cs|165|
|Error|CS1061|'ExcelChartLegend' does not contain a definition for 'Entries' and no accessible extension method 'Entries' accepting a first argument of type 'ExcelChartLegend' could be found|\15-ChartsAndThemes\ColumnChartsWithLegendSample.cs|33|
|Error|CS1061|'ExcelChartLegend' does not contain a definition for 'Entries' and no accessible extension method 'Entries' accepting a first argument of type 'ExcelChartLegend' could be found|\15-ChartsAndThemes\ColumnChartsWithLegendSample.cs|34|
|Error|CS1061|'ExcelChartLegend' does not contain a definition for 'Entries' and no accessible extension method 'Entries' accepting a first argument of type 'ExcelChartLegend' could be found|\15-ChartsAndThemes\ColumnChartsWithLegendSample.cs|35|

**Comment by JanKallman** [comment]
Sorry about that. We are releasing 5.8 right now, so a it will work in a moment.

**Comment by JanKallman** [comment]
EPPlus 5.8 is now published, so please run `git pull` and it should work. Sorry for the inconvenience.
