### ISSUE TITLE
Tamaño checkbox

### ISSUE THREAD

**Issue by luis-cosillo** [EPPlusSoftware/EPPlus.Sample.NetCore#9]
Porque al utilizar este codigo, no le pone el tamaño y lugar donde lo quiero, alguien que pueda ayudarme, talvez algun parametro me hace falta.

                var chkFemenino = ws.Drawings.AddCheckBoxControl("Checkbox1");
                chkFemenino.DefaultSize = true;
                chkFemenino.SetSize(40, 31);
                chkFemenino.SetPosition(3, 1, 1, 0);
                chkFemenino.AdjustPositionAndSize();
                chkFemenino.Checked = eCheckState.Checked;
                chkFemenino.Text = "Femenino";

**Comment by JanKallman** [comment]
Sorry for the late replay. You should be able to set this with the SetPosition and SetSize methods
